GPUID: 0
WORKERS: 8
PRINT_FREQ: 100
SAVE_FREQ: 5
PIN_MEMORY: True
# 保存位置
OUTPUT_DIR: 'output'

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASET:
  DATASET: leiguan
  ROOT: ""
  # CHAR_FILE: 'lib/dataset/txt/chars_5990.txt'
  CHAR_FILE: 'lib/dataset/txt/plate3.txt'
  # 数据集位置
  JSON_FILE: {'train': 'datasets/train.txt', 'val': 'datasets/val.txt'}
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588
  ALPHABETS: 'QWERTYUIOPASDFGHJKLZXCVBNM0123456789'

TRAIN:
  BATCH_SIZE_PER_GPU: 512
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME:
    IS_RESUME: True
    FILE: 'checkpoint_49_acc_0.9933.pth'
  OPTIMIZER: 'sgd'
  LR: 0.005
  WD: 0.0
  LR_STEP: [60, 80]
  # LR_STEP: [40,80,120,180]
  LR_FACTOR: 0.1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:
  # 微调
  FINETUNE:
    IS_FINETUNE: True
    FINETUNE_CHECKPOINIT: 'B_9921.pth'
    FREEZE: true

TEST:
  BATCH_SIZE_PER_GPU: 128
  SHUFFLE: True  # for random test rather than test on the whole validation set
  NUM_TEST: 1000
  NUM_TEST_DISP: 10

MODEL:
  NAME: 'crnn'
  IMAGE_SIZE:
    OW: 280 # origial width: 280
    H: 32
    W: 100   # resized width: 160
  NUM_CLASSES: 0
  NUM_HIDDEN: 256

